# Generated by Django 2.2.16 on 2022-11-09 02:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Нужно указать количество.'), django.core.validators.MaxValueValidator(10000, 'Слишком большое количество')], verbose_name='Количество')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название ингридиента')),
                ('measure', models.CharField(max_length=128, verbose_name='Единицы измерения')),
            ],
            options={
                'verbose_name': ('Ингридиент',),
                'verbose_name_plural': ('Ингридиенты',),
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('color', models.CharField(blank=True, default='FFFFFF', max_length=6, null=True, verbose_name='Цветовой HEX-код')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг тэга')),
            ],
            options={
                'verbose_name': ('Тег',),
                'verbose_name_plural': ('Теги',),
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название рецепта')),
                ('image', models.ImageField(upload_to='images_recipe/', verbose_name='Изображение для рецепта')),
                ('description', models.TextField(max_length=2048, verbose_name='Описание')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('time_cooking', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Нужно указать количество.'), django.core.validators.MaxValueValidator(10000, 'Слишком большое количество')], verbose_name='Время приготовления в минутах')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('cart', models.ManyToManyField(related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='Список покупок')),
                ('favorite', models.ManyToManyField(related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Избранные рецепты')),
                ('ingredients', models.ManyToManyField(related_name='ingredients', through='recipes.AmountIngredient', to='recipes.Ingredient', verbose_name='Ингридиенты для рецепта')),
                ('tags', models.ManyToManyField(related_name='tags', to='recipes.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': ('Рецепт',),
                'verbose_name_plural': ('Рецепты',),
                'ordering': (('-pub_date',),),
            },
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='unique_for_ingredient'),
        ),
        migrations.AddField(
            model_name='amountingredient',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='recipes.Ingredient', verbose_name='Связанные ингредиенты'),
        ),
        migrations.AddField(
            model_name='amountingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='recipes.Recipe', verbose_name='В каких рецептах'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('name', 'author'), name='unique_for_author'),
        ),
        migrations.AddConstraint(
            model_name='amountingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredients'), name='%(app_label)s_%(class)s ingredient alredy added\n'),
        ),
    ]
