# Generated by Django 2.2.16 on 2022-11-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-pub_date',), 'verbose_name': ('Рецепт',), 'verbose_name_plural': ('Рецепты',)},
        ),
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='unique_for_ingredient',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='measure',
            new_name='measurement_unit',
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, null=True, verbose_name='Цветовой HEX-код'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug тега'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='unique_for_ingredient'),
        ),
    ]
