# Generated by Django 2.2.16 on 2022-11-09 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20221109_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_cooking',
            new_name='cooking_time',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
    ]
