# Generated by Django 2.2.16 on 2022-11-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20221109_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='media/recipes/images/', verbose_name='Изображение для рецепта'),
        ),
    ]
